#6 Director full info
AlenaKharytonchyk/CodeJam-Culture-Portal_gr24 pull request #17
Opened 2019-01-26 19:26 UTC by VictoriaTheBrave

*What was done?*
add current director component (tab)
*What problems did you have?*
I'm not sure about parameter I pass to function (just director name)
*What wasn-t done and why?*
We need to add components we do separately (like Youtube and so on)

2019-01-26 20:08 UTC, AlenaKharytonchyk commented
Вика, перенеси все таки эту страницу в папку components, потому что это будет как часть страницы Directors, всплывающая по нажатию

2019-01-26 20:09 UTC, AlenaKharytonchyk requested changes

2019-01-26 20:09 UTC, AlenaKharytonchyk commented on theatre-directors/src/pages/CurrentDirector.jsx
>        </div>
Предлагаю использовать компонет GeneralInfo.jsx 
А саму структуру перенести в этот компонет. 
`<GeneralInfo />`
Это переносим в компонет GeneralInfo.jsx:
`<div>
        <h3>Биография</h3>
        <div></div>
        <div />
      </div>`

2019-01-26 20:09 UTC, AlenaKharytonchyk commented on theatre-directors/src/pages/CurrentDirector.jsx
>          <h3>Список произведений</h3>
По аналогии с GeneralInfo переносим в TimeLine

2019-01-26 20:09 UTC, AlenaKharytonchyk commented on theatre-directors/src/pages/CurrentDirector.jsx
>          <h3>Фото</h3>
По аналогии с GeneralInfo переносим в Gallery.jsx

2019-01-26 20:09 UTC, AlenaKharytonchyk commented on theatre-directors/src/pages/CurrentDirector.jsx
>          <h3>Видео</h3>
По аналогии с GeneralInfo переносим в Youtube.jsx

2019-01-26 20:09 UTC, AlenaKharytonchyk commented on theatre-directors/src/pages/CurrentDirector.jsx
>          <h3>Место основной деятельности</h3>
По аналогии с GeneralInfo переносим в Map.jsx
Метод initMap должен быть вызван в методе onComponentDidMount компонентом Map.jsx. Можешь глянуть жизненный цикл реакт компонента

2019-01-27 11:05 UTC, 375291601334 commented
Seems good to me.

2019-01-27 11:09 UTC, 375291601334 approved these changes
Seems good

2019-01-27 11:10 UTC, merged